- README.md
- slog/go.mod
- slog/go.sum
- slog/slog.go
- slog/slog_test.go
- slog/tracing/tracing.go
Just adding our current slog. After we tag it we can start improving. Already have better ideas on how to handle adding fields and propagating the log context (the current way doesn't scale well and involve custom handlers). So we should have some improvements on the API coming soon.
The slog library is a thin wrapper around the experimental standard structured log that will be added on Go soon (it was already accepted). We can shift to the standard lib implementation with no impact on our code + there is some extra functionality that a more general/standard library won't do, ours is more specific in assuming things like tracing and config loading from env vars.
> feat: add first slog version

- tracing/README.md
- tracing/tracing.go
- tracing/tracing_test.go
Adds a way to add org_id and trace_id on contexts and retrieve them. Also add the trace id on the context on the instrumentation code, so not only a logger instance is available, but also the trace ID.
The idea is to use this as a building block for a common publisher code, that will automatically retrieve trace ID + org ID to use on events.
> feat:tracing: add ctx keys

- event/event.go
- event/event_test.go
- event/go.mod
- event/go.sum
Add a first raw subscription that delivers any message. We will build a more specific one on top of this that will handle our events envelopes. A follow up PR will add the subscription that we will usually use more, this one is suitable for legacy events that don't follow our new envelope format.
> feat: add raw subscription

- event/metrics.go
We need bigger buckets, some processing takes easily more than 30 sec, then metrics get saturated on that value.
> feat: improve event metrics buckets

- tracing/tracing.go
When retrying some requests we use the same trace_id, then it is harder to be sure you are seeing request X handling trace Y. Adding a simple/unique per request ID, in these situations it can be used to be sure you are analyzing a single request flow (not others that had the same trace_id, logs can be unordered, so it gets messy).
> chore: add request_id to http requests

- service/README.md
- service/metrics.go
- service/metrics_test.go
To avoid duplicating the basic metric instrumentation code + help us export consistent metrics across different services, at least for basic HTTP stuff (services still can have optional domain specific metrics).
> feat: add basic http instrumentation/metrics

- event/event.go
To handle situations where clients may send multiple requests with the same trace_id. We have some more details about this on our handbook, the idea is to have something that is GUARANTEED to be unique and per request/event/msg, independent of client behavior/etc, so filtering logs per request context is always trivial (and trace IDs can be used to correlate things across service boundaries).
Events are not request, but we want to have a common/unique name...and we went with request_id for now.
> chore: add request_id to each event

- event/event.go
If you want to test a MessageHandler you need to be able to create a Message to pass as a parameter. The current design doesn't allow it. Im not sure about the design of Message...my idea was to push into the direction of making the message immutable (quite a good property when debugging odd scenarios on message handling), but doing that in Go is not trivial (requires copying the []byte when accessing it..or else it is mutable anyway...)...so Im not sure the abstraction is worth its cost...Im open to alternatives..but keeping in line with the current abstraction would be to allow for it to be built with a function (since the fields are private).
> feat: add event.NewMessage function

- slog/slog.go
- slog/slog_test.go
Useful on CLI applications that tend to fatal/abort on some invariants/conditions.
> feat: extend slog.Logger with Fatal method

- event/event.go
- event/event_test.go
Avoid crashing the entire program when the handling of a single event panics.
Very similar (and with copied code :-)) to Go's http stdlib.
> feat: event: handle panics on event handling

- xhttp/client.go
- xhttp/client_test.go
Since in some cases bodies are guaranteed to be non-nil (even if empty, on http.NewRequest()) I thought this was OK, but it wasn't...it segfaults...hard :rofl: (should have checked this anyway... plain stupid shit). Im in a rush so the tests are not great..but they do cover this now
> fix: only read non nil bodies on requests

- xhttp/client.go
- xhttp/client_test.go
- xhttptest/client.go
When we create per requests contexts we were cancelling the contexts before when we returning from Do,
this caused responses to fail when they are being read, since the response reading is part of the
original request context (and then can timeout/get cancelled).
> fix: context cancellation with per request timeouts

- event/event.go
When event.MessageSubscription catches a panic in the message handler, we end up with this confusing error in the logs:
!ERROR:json: unsupported type: func(func(inte
This change should result in a more useful log.
> event: better log message for panic recovery

- xhttp/client.go
- xhttp/client_opts.go
- xhttp/client_test.go
This is a first building block for adding some client side metrics (also logging when desired).
> feat: add callback for requests on xhttp.RetrierClient

- xhttp/client.go
- xhttp/client_opts.go
- xhttp/client_test.go
It overlaps a little with the on request done callback, but makes it easier to inspect when the retrier decided to retry some error, so building logging/metrics for retries will be more straightforward.
> feat: add on retry callback for xhttp.NewRetrierClient

- xhttp/client.go
- xhttp/client_opts.go
- xhttp/client_test.go
I want to start using the retrierClient to retry on status 429, but it seems like then we should also use the Retry-After header.
> xhttp.Client: follow Retry-After header

- xtime/range.go
- xtime/range_test.go
1 - Guarantee ranges can't be changed after they are created
2 - Ensure invariant that start <= end
Functions receiving this type as a parameter can then be sure they don't need to validate anything (zero value is valid..although kinda useless  :laughing: ).
> feat: make xtime.Range immutable and ensure invariants

- slog/slog.go
- slog/slog_test.go
Export the current google cloud handler as a function. Makes it easier for clients to create customized slog.Loggers (winking at @gustavom2998 :smile: ).
Also add some more aliases/slog.New to make it easier to create new sloggers that are not the default.
> feat: add slog.NewGoogleCloudHandler

- event/event_test.go
- justfile
- service/metrics_test.go
- tracing/tracing.go
- tracing/tracing_test.go
Some services handle way too much requests (dozens of millions per day). Logging each single request on the
INFO level is starting to generate considerable costs (and we rarely need those logs..if ever). In order to be
able to change this behavior Im introducing a new type and a callback for the request stats. The current default
behavior will be maintained.
> feat:tracing: add fine grained control over request stats

- event/event.go
- event/event_test.go
This will make batching easier. We usually deal with one event at a time in a "handler" fashion, but sometimes we need to batch N events together in memory (usually to optimize some processing, which is the case right now). This PR introduces the basics for using subscriptions with a Receive method, similar to the one on Go CDK but with our event envelope and also a ReceiveN that will help with batching.
> feat: add Subscription.ReceiveN

- xhttp/request.go
- xhttp/xhttp.go
- xhttp/xhttp_test.go
My idea is to add a layer as small as possible just to make it easier to handle JSON on HTTP request/responses. Usually errors are disjointed from responses (different fields), so I'm thinking on always creating a type that is the union of whatever you expect as response + what you would expect if it is an error. After checking the status code then you can validate each part of the parsed data, the error for an error status code and the valid response for a success. This allows for more sophisticated things to be built on top, like something that already checks the status code and hides HTTP entirely, but not sure that is necessary/desirable once we have something that already makes it considerably less annoying to receive JSON (no more reading/error handling/parsing for every request). …
> feat: add xhttp.NewJSONRequest

- xhttp/xhttp.go
- xhttp/xhttp_test.go
Should be useful mostly for debugging, but can help when an endpoint is sending you some JSON but it is different from what you expected (so parsing succeeds but information is not there).
Also renaming Obj to Value, Obj assumed too much about the structure.
> feat: add xhttp.Response.RawBody

- xjson/xjson.go
- xjson/xjson_test.go
Sometimes I do the 3 return values things for some stupid reason because I almost always regret it later. In a lot of use cases I don't care if it failed for an error or was just not found (and for debugging/logging the error message will be enough to make it clear), handling the result gets considerably more annoying (I might be traumatized by io.EOF...but not found issues are not the same thing I think).
> redesign: xjson.DynGet with value,err instead of 3 return vals

- tracing/tracing.go
- tracing/tracing_test.go
We already had the request_id but only for logs. The request ID is good to identify specific request/responses when the same trace_id may be used (like in a retry). It is a more limited version of a span ID for tracing, but it is what we have today (we may have something more complete someday). With this we can add the request ID as metadata in an event related to a request and then easily correlate them (the trace ID is not enough...but maybe that is debatable...but right now I also don't have a whole lot of time).
> feat: add tracing context request ID

- xhttp/retrier.go
Add `502 Bad Gateway` and `429 Too Many Requests` as retryable status codes.
> feat(xhttp): add more retryable status codes.

- xhttp/retrier.go
Mostly for debugging purposes :-). Always reading the response body in the core library doesn't sound like a good idea, but I need to log this in some wonky situations.
> fix(xhttp): allow on retry callback to read the response body
